services:
    phd_exceptional_validation:
        class: PhPhD\ExceptionalValidationBundle\Messenger\ExceptionalValidationMiddleware
        arguments:
            - '@phd_exceptional_validation.handler'

    phd_exceptional_validation.handler:
        class: PhPhD\ExceptionalValidation\Handler\ExceptionHandler
        arguments:
            - '@phd_exceptional_validation.exception_capturer'

    phd_exceptional_validation.exception_capturer:
        class: PhPhD\ExceptionalValidation\Capturer\CaptureTreeExceptionCapturer
        arguments:
            - '@phd_exceptional_validation.capture_tree_assembler'

    phd_exceptional_validation.capture_tree_assembler:
        class: PhPhD\ExceptionalValidation\Assembler\Object\CapturableObjectViaReflectionTreeAssembler
        arguments:
            - '@phd_exceptional_validation.capturable_properties_assembler'

    phd_exceptional_validation.capturable_properties_assembler:
        class: PhPhD\ExceptionalValidation\Assembler\Property\CapturablePropertiesViaReflectionAssembler
        arguments:
            - '@phd_exceptional_validation.capture_list_assembler'

    phd_exceptional_validation.capture_list_assembler:
        class: PhPhD\ExceptionalValidation\Assembler\CaptureList\CompositeCaptureListAssembler
        arguments:
            - !tagged_iterator phd_exceptional_validation.capture_list_assembler
